export const GET_SINGLE_WORD_SUCCESS = "GET_SINGLE_WORD_SUCCESS";
export const GET_SINGLE_WORD_ERROR = "GET_SINGLE_WORD_ERROR";
export const GET_MULTIPLE_WORD = "GET_MULTIPLE_WORD";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const CLEAR_INFO_USER = "CLEAR_INFO_USER";

export const GET_LIST_WORD = "GET_LIST_WORD";
export const CLEAR_LIST_WORD = "CLEAR_LIST_WORD";
export const ADD_TO_LIST_WORD_SUCCESS = "ADD_TO_LIST_WORD_SUCCESS";
export const ADD_TO_LIST_WORD_ERROR = "ADD_TO_LIST_WORD_ERROR";
export const REMOVE_FROM_LIST_WORD_SUCCESS = "REMOVE_FROM_LIST_WORD_SUCCESS";
export const REMOVE_FROM_LIST_WORD_ERROR = "REMOVE_FROM_LIST_WORD_ERROR";

export const TOGGLE_THEME = "TOGGLE_THEME";

export const CLEAR_ERROR_WORD = "CLEAR_ERROR_WORD";
export const CLEAR_ERROR_SEARCH = "CLEAR_ERROR_SEARCH";

export const SET_MESSAGE = "SET_MESSAGE";

export const LOADING = "LOADING";
